### ISSUE TITLE
Question about performance/getResourceAsStream()

### ISSUE THREAD

**Issue by MenoData** [JakeWharton/ThreeTenABP#1]
As you explained the main motivation to wrap Threeten-backport for Android is to avoid the method `ClassLoader.getResourceAsStream()`. I have two questions:

a) Have you observed any performance gains or done some micro benchmark tests?

b) Are you aware of following Google-issues and commits which might make your approach obsolete in the future?  I would be graceful for any opinions and estimations which can help to widen our understanding for the resource-loading-issue on Android.
- https://android.googlesource.com/platform/libcore/+/05a5c2f89e12e27db69f24165a05bdfd0476c73a
- https://code.google.com/p/android/issues/detail?id=60071

**Comment by dlew** [comment]
Interesting!

a) I've never conducted any performance tests but it'd be interesting to compare loading via the resource system vs. the classloader, especially since the commit you linked is directly related to that.

b) I wonder if this would mean the library wouldn't have to include the tzdata; then we could just have a custom `TzdbZoneRulesProvider` that simply calls `setCaches()`.

    On the other hand, the performance hit might be reason enough to not use it, if it means that you're adding a couple hundred milliseconds during initialization.

**Comment by JakeWharton** [comment]
I did a few benchmarks the weekend before last and got around 1-2ms of loading time. I did not bother comparing with the jar resources version due to Dan's blog post and approach on the Joda variant.

As to performance in general, I think I might be more interested in compiling our own TZDB format which allows us to lazy-load individual pieces from it as they're used. I haven't looked into much, just wanted to get this library up and start experimenting.

**Comment by AndroidDeveloperLB** [comment]
I did some comparison of the most simple way for Joda vs ThreeTen vs ThreeTenABP :

![image](https://user-images.githubusercontent.com/5357526/47642160-98bad000-db70-11e8-8044-80c1da826197.png)

Each is a different app, of course. 

What I did is to init the library (if needed) , and get the current time, twice. I measured the time of each of those things.

I don't know about memory usage, but it seems that Joda and ThreeTenABP have better speed of first usage than the normal ThreeTen library.
