### ISSUE TITLE
getHours(), getMinutes(), and getSeconds()

### ISSUE THREAD

**Issue by HasanElHefnawy** [JakeWharton/ThreeTenABP#109]
In Class Duration, the methods toHours(), toMinutes(), toSeconds() are great, but I think it'll be nice if we also have methods getHours(), getMinutes(), and getSeconds() that work in the same way as they do in this [library](https://github.com/dlew/joda-time-android).

**Comment by JakeWharton** [comment]
The behavior of this library comes from ThreeTenBP which is now baked into the JDK as java.time. Any behavior changes will have to go into the JDK before they can be ported to ThreeTenBP which will then be picked up by this library.

Also the guy who wrote Joda Time built java.time and ThreeTenBP so behavior changes are likely intentional.
