### ISSUE TITLE
Calculation problem

### ISSUE THREAD

**Issue by lsgmkk** [JakeWharton/ThreeTenABP#118]
I used this to calculate HijrahDate, but the result is not the same as the result of DateTime using Android 8.0
For example, if I calculate today's HijrahDate 2020-1-6, the result is 1441/5/10
But the result I calculated using the method provided by 8.0 is 1441/5/11
Below is my code: 

    @RequiresApi(Build.VERSION_CODES.O)
    fun test() {
        var hijrahDate = HijrahDate.now()
        var pattern = org.threeten.bp.format.DateTimeFormatter.ofPattern("MM/dd/yyyy")
        var s = pattern.format(hijrahDate)
        Log.e("TAG", "test 1-------->$s")

        var ofPattern = DateTimeFormatter.ofPattern("MM/dd/yyyy")
        var now = java.time.chrono.HijrahDate.now()
        var format = ofPattern.format(now)
        Log.e("TAG", "test 2--------->$format")
    }

Is this what is the reason?

**Comment by lsgmkk** [comment]
The result of test 1 is 5/10/1441
The result of test 2 is 5/11/1441

**Comment by JakeWharton** [comment]
This library is just a repackaging of the timezone database for use on Android. Any problems with the timezone database or the ThreeTenBP library itself should be filed on https://github.com/ThreeTen/threetenbp/.

**Comment by MenoData** [comment]
@lsgmkk The threetenBP-library and its wrapper specialized for Android here does NOT support the umalqura-calendar of Saudi-Arabia. I suspect that is what you want. Well, Java-8+ supports it, but ThreetenBP has not backported it. See also this [old issue](https://github.com/ThreeTen/threetenbp/issues/66). So the author S. Colebourne is surely aware of the problem but does not managed to solve it for whatever reason. 

The library Threeten-Extra is obviously the wrong place to post a new issue because it will not backport anything from standard Java but is just intended as small enhancement.

The best you can do is probably using another library like

1. [msarhan](https://github.com/msarhan/ummalqura-calendar)
2. [Time4A](https://github.com/MenoData/Time4A) (my lib)

**Comment by lsgmkk** [comment]
ok,thank




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Meno Hochschild"<notifications@github.com&gt;; 
发送时间: 2020年1月8日(星期三) 下午5:11
收件人: "JakeWharton/ThreeTenABP"<ThreeTenABP@noreply.github.com&gt;; 
抄送: "恭喜你获得腾讯官方"<1142163805@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [JakeWharton/ThreeTenABP] Calculation problem (#118)




@lsgmkk The threetenBP-library and its wrapper specialized for Android here does NOT support the umalqura-calendar of Saudi-Arabia. I suspect that is what you want. Well, Java-8+ supports it, but ThreetenBP has not backported it. See also this old issue. So the author S. Colebourne is surely aware of the problem but does not managed to solve it for whatever reason.
 
The library Threeten-Extra is obviously the wrong place to post a new issue because it will not backport anything from standard Java but is just intended as small enhancement.
 
The best you can do is probably using another library like
  
msarhan
 
Time4A (my lib)
