### ISSUE TITLE
Contribution: Gson.toJson with @Expose annotations error

### ISSUE THREAD

**Issue by OscarCaro** [JakeWharton/ThreeTenABP#123]
I have a class with a LocalDate attribute. I needed to store objects of that class in SharedPreferences,  for which I used Gson.toJson to serialize the object to a String. I also needed to select manually which attributes to store and which not, and so I use the Gson @Expose annotations.
But even though I marked the date with the @Expose, I wasn't being stored, since the internal attributes of the LocalDate didn't have the @Expose. 
To fix that issue, I had to create custom JsonSerializers and JsonDeserializers.
Now it's working smoothly, but I was wondering if I could contribute to your project by adding this serializers directly to the library.
Have a nice day!

**Comment by JakeWharton** [comment]
So three things here:

1. Gson is effectively deprecated and replaced by [Moshi](https://github.com/square/moshi) which is built by the same people but with a lot of the faults of Gson corrected.

2. You should never serialize types that you do not control using their implementations. Always write a custom adapter to use their public API. The fact that Gson didn't work because of the lack of `@Expose` annotations is a happy accident because the implementation of these types is not stable and may change at any time.

3. I do not want to publish adapters for Gson or Moshi or any serialization library as part of this library. For Gson and Moshi please see this thread: https://github.com/JakeWharton/ThreeTenABP/issues/67. These adapters can be published as a standalone library (targeting ThreeTenBp, not ThreeTenABP) and used together.

If you decide to publish these as a new standalone library, though, feel free to link it here.
