### ISSUE TITLE
Post approximate size of finished build, and post number of methods.

### ISSUE THREAD

**Issue by basil-bourque** [JakeWharton/ThreeTenABP#36]
Some people hesitate to add a library such as this to their Android project because of concern over increasing the size of their app or hitting the 65K limit of methods allowed by Android. 

Posting on the main page of this project site (a) the approximate size and (b) method count would help developers make an informed decision.

**Comment by ming13** [comment]
You can use services such as [Methods Count](http://www.methodscount.com/).

**Comment by JakeWharton** [comment]
I think this is true of every library and the number of methods will vary based on what you are already using in java.* that overlaps and whether or not you're using ProGuard/R8. I think it's better to use a tool that allows you to figure this out for any library on demand rather than requiring every library to provide this info.
