### ISSUE TITLE
TemporalAccessor API different from Java8

### ISSUE THREAD

**Issue by msrd0** [JakeWharton/ThreeTenABP#63]
For those that are trying to derive their own class from `TemporalAccessor` might notice that in Java8 (see the source code [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/temporal/TemporalAccessor.java)) the [`get`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAccessor.html#get-java.time.temporal.TemporalField-), [`query`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAccessor.html#query-java.time.temporal.TemporalQuery-) and [`range`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAccessor.html#range-java.time.temporal.TemporalField-) methods are default methods means one does not have to override them. However, on Android I have to override those methods.

I know that the interface is marked as a framework-level interface, however reading the javadoc makes me believe that one does not necessarily want to avoid users creating subtypes but rather make them use specific types instead of generic ones. Please correct me if I'm wrong or point me to a better solution if there is one. The reason why I'm trying to inherit from `TemporalAccessor` is because [`DateTimeFormatter.format`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#format-java.time.temporal.TemporalAccessor-) takes a `TemporalAccessor` as an argument.

**Comment by JakeWharton** [comment]
The API of this artifact comes from ThreeTenBP. This is only an
Android-specific bundling of the timezone database. You'll want to ask your
question on that project.

**Comment by MenoData** [comment]
Out of curiosity: What kind of problem do you want to solve? Which kind of `TemporalAccessor`-subclass do you have in mind?

**Comment by msrd0** [comment]
@MenoData I'm trying to create a class that handles time differences and that can be printed with a `DateTimeFormatter`

**Comment by msrd0** [comment]
@JakeWharton Thanks, I reported it: https://github.com/ThreeTen/threetenbp/issues/78

**Comment by MenoData** [comment]
@msrd0 Oh this is not a good idea because a `TemporalAccessor` is NOT a duration (or any other kind of `TemporalAmount`). And a `DateTimeFormatter` is not designed for printing durations.

You will need a printer for `TemporalAmount` instead, something like what I have already written in my time library Time4J, either [pattern-based](http://time4j.net/javadoc-en/net/time4j/Duration.Formatter.html#format-java.time.temporal.TemporalAmount-) or [localized for many languages](http://time4j.net/javadoc-en/net/time4j/PrettyTime.html#print-java.time.temporal.TemporalAmount-). For Android, the version Time4A uses its own duration types only (which are more powerful however) because JSR-310 is not available below api-level 26.

I doubt if reinventing the wheel is necessary ;-)

**Comment by msrd0** [comment]
@MenoData Well, I don't really care if `DateTimeFormatter` was designed for printing durations because it works like I expect it. I agree that Android APIs are crap, but I might check out Time4J if that does what I need (I already have a somewhat complete class for the difference that works on Oracle JDK so I just looked for java.time on Android).
